package countries

var countries = []Country{
	{
		Name:            "Абхазия",
		FullName:        "Республика Абхазия",
		English:         "Abkhazia",
		Alpha2:          "AB",
		Alpha3:          "ABH",
		ISO:             "895",
		Location:        "Азия",
		LocationPrecise: "Закавказье",
	},
	{
		Name:            "Австралия",
		FullName:        "",
		English:         "Australia",
		Alpha2:          "AU",
		Alpha3:          "AUS",
		ISO:             "036",
		Location:        "Океания",
		LocationPrecise: "Австралия и Новая Зеландия",
	},
	{
		Name:            "Австрия",
		FullName:        "Австрийская Республика",
		English:         "Austria",
		Alpha2:          "AT",
		Alpha3:          "AUT",
		ISO:             "040",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Азербайджан",
		FullName:        "Республика Азербайджан",
		English:         "Azerbaijan",
		Alpha2:          "AZ",
		Alpha3:          "AZE",
		ISO:             "031",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Албания",
		FullName:        "Республика Албания",
		English:         "Albania",
		Alpha2:          "AL",
		Alpha3:          "ALB",
		ISO:             "008",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Алжир",
		FullName:        "Алжирская Народная Демократическая Республика",
		English:         "Algeria",
		Alpha2:          "DZ",
		Alpha3:          "DZA",
		ISO:             "012",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Американское Самоа",
		FullName:        "",
		English:         "American Samoa",
		Alpha2:          "AS",
		Alpha3:          "ASM",
		ISO:             "016",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Ангилья",
		FullName:        "",
		English:         "Anguilla",
		Alpha2:          "AI",
		Alpha3:          "AIA",
		ISO:             "660",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Ангола",
		FullName:        "Республика Ангола",
		English:         "Angola",
		Alpha2:          "AO",
		Alpha3:          "AGO",
		ISO:             "024",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Андорра",
		FullName:        "Княжество Андорра",
		English:         "Andorra",
		Alpha2:          "AD",
		Alpha3:          "AND",
		ISO:             "020",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Антарктида",
		FullName:        "",
		English:         "Antarctica",
		Alpha2:          "AQ",
		Alpha3:          "ATA",
		ISO:             "010",
		Location:        "Антарктика",
		LocationPrecise: " ",
	},
	{
		Name:            "Антигуа и Барбуда",
		FullName:        "",
		English:         "Antigua and Barbuda",
		Alpha2:          "AG",
		Alpha3:          "ATG",
		ISO:             "028",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Аргентина",
		FullName:        "Аргентинская Республика",
		English:         "Argentina",
		Alpha2:          "AR",
		Alpha3:          "ARG",
		ISO:             "032",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Армения",
		FullName:        "Республика Армения",
		English:         "Armenia",
		Alpha2:          "AM",
		Alpha3:          "ARM",
		ISO:             "051",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Аруба",
		FullName:        "",
		English:         "Aruba",
		Alpha2:          "AW",
		Alpha3:          "ABW",
		ISO:             "533",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Афганистан",
		FullName:        "Переходное Исламское Государство Афганистан",
		English:         "Afghanistan",
		Alpha2:          "AF",
		Alpha3:          "AFG",
		ISO:             "004",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Багамы",
		FullName:        "Содружество Багамы",
		English:         "Bahamas",
		Alpha2:          "BS",
		Alpha3:          "BHS",
		ISO:             "044",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Бангладеш",
		FullName:        "Народная Республика Бангладеш",
		English:         "Bangladesh",
		Alpha2:          "BD",
		Alpha3:          "BGD",
		ISO:             "050",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Барбадос",
		FullName:        "",
		English:         "Barbados",
		Alpha2:          "BB",
		Alpha3:          "BRB",
		ISO:             "052",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Бахрейн",
		FullName:        "Королевство Бахрейн",
		English:         "Bahrain",
		Alpha2:          "BH",
		Alpha3:          "BHR",
		ISO:             "048",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Беларусь",
		FullName:        "Республика Беларусь",
		English:         "Belarus",
		Alpha2:          "BY",
		Alpha3:          "BLR",
		ISO:             "112",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Белиз",
		FullName:        "",
		English:         "Belize",
		Alpha2:          "BZ",
		Alpha3:          "BLZ",
		ISO:             "084",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Бельгия",
		FullName:        "Королевство Бельгии",
		English:         "Belgium",
		Alpha2:          "BE",
		Alpha3:          "BEL",
		ISO:             "056",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Бенин",
		FullName:        "Республика Бенин",
		English:         "Benin",
		Alpha2:          "BJ",
		Alpha3:          "BEN",
		ISO:             "204",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Бермуды",
		FullName:        "",
		English:         "Bermuda",
		Alpha2:          "BM",
		Alpha3:          "BMU",
		ISO:             "060",
		Location:        "Америка",
		LocationPrecise: "Северная Америка",
	},
	{
		Name:            "Болгария",
		FullName:        "Республика Болгария",
		English:         "Bulgaria",
		Alpha2:          "BG",
		Alpha3:          "BGR",
		ISO:             "100",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Боливия",
		FullName:        "Многонациональное Государство Боливия",
		English:         "Bolivia, plurinational state of",
		Alpha2:          "BO",
		Alpha3:          "BOL",
		ISO:             "068",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Бонайре, Саба и Синт-Эстатиус",
		FullName:        "",
		English:         "Bonaire, Sint Eustatius and Saba",
		Alpha2:          "BQ",
		Alpha3:          "BES",
		ISO:             "535",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Босния и Герцеговина",
		FullName:        "",
		English:         "Bosnia and Herzegovina",
		Alpha2:          "BA",
		Alpha3:          "BIH",
		ISO:             "070",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Ботсвана",
		FullName:        "Республика Ботсвана",
		English:         "Botswana",
		Alpha2:          "BW",
		Alpha3:          "BWA",
		ISO:             "072",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Бразилия",
		FullName:        "Федеративная Республика Бразилия",
		English:         "Brazil",
		Alpha2:          "BR",
		Alpha3:          "BRA",
		ISO:             "076",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Британская территория в Индийском океане",
		FullName:        "",
		English:         "British Indian Ocean Territory",
		Alpha2:          "IO",
		Alpha3:          "IOT",
		ISO:             "086",
		Location:        "Океания",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Бруней-Даруссалам",
		FullName:        "",
		English:         "Brunei Darussalam",
		Alpha2:          "BN",
		Alpha3:          "BRN",
		ISO:             "096",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Буркина-Фасо",
		FullName:        "",
		English:         "Burkina Faso",
		Alpha2:          "BF",
		Alpha3:          "BFA",
		ISO:             "854",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Бурунди",
		FullName:        "Республика Бурунди",
		English:         "Burundi",
		Alpha2:          "BI",
		Alpha3:          "BDI",
		ISO:             "108",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Бутан",
		FullName:        "Королевство Бутан",
		English:         "Bhutan",
		Alpha2:          "BT",
		Alpha3:          "BTN",
		ISO:             "064",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Вануату",
		FullName:        "Республика Вануату",
		English:         "Vanuatu",
		Alpha2:          "VU",
		Alpha3:          "VUT",
		ISO:             "548",
		Location:        "Океания",
		LocationPrecise: "Меланезия",
	},
	{
		Name:            "Венгрия",
		FullName:        "Венгерская Республика",
		English:         "Hungary",
		Alpha2:          "HU",
		Alpha3:          "HUN",
		ISO:             "348",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Венесуэла",
		FullName:        "Боливарийская Республика Венесуэла",
		English:         "Venezuela",
		Alpha2:          "VE",
		Alpha3:          "VEN",
		ISO:             "862",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Виргинские острова, Британские",
		FullName:        "Британские Виргинские острова",
		English:         "Virgin Islands, British",
		Alpha2:          "VG",
		Alpha3:          "VGB",
		ISO:             "092",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Виргинские острова, США",
		FullName:        "Виргинские острова Соединенных Штатов",
		English:         "Virgin Islands, U.S.",
		Alpha2:          "VI",
		Alpha3:          "VIR",
		ISO:             "850",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Вьетнам",
		FullName:        "Социалистическая Республика Вьетнам",
		English:         "Vietnam",
		Alpha2:          "VN",
		Alpha3:          "VNM",
		ISO:             "704",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Габон",
		FullName:        "Габонская Республика",
		English:         "Gabon",
		Alpha2:          "GA",
		Alpha3:          "GAB",
		ISO:             "266",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Гаити",
		FullName:        "Республика Гаити",
		English:         "Haiti",
		Alpha2:          "HT",
		Alpha3:          "HTI",
		ISO:             "332",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Гайана",
		FullName:        "Республика Гайана",
		English:         "Guyana",
		Alpha2:          "GY",
		Alpha3:          "GUY",
		ISO:             "328",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Гамбия",
		FullName:        "Республика Гамбия",
		English:         "Gambia",
		Alpha2:          "GM",
		Alpha3:          "GMB",
		ISO:             "270",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Гана",
		FullName:        "Республика Гана",
		English:         "Ghana",
		Alpha2:          "GH",
		Alpha3:          "GHA",
		ISO:             "288",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Гваделупа",
		FullName:        "",
		English:         "Guadeloupe",
		Alpha2:          "GP",
		Alpha3:          "GLP",
		ISO:             "312",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Гватемала",
		FullName:        "Республика Гватемала",
		English:         "Guatemala",
		Alpha2:          "GT",
		Alpha3:          "GTM",
		ISO:             "320",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Гвинея",
		FullName:        "Гвинейская Республика",
		English:         "Guinea",
		Alpha2:          "GN",
		Alpha3:          "GIN",
		ISO:             "324",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Гвинея-Бисау",
		FullName:        "Республика Гвинея-Бисау",
		English:         "Guinea-Bissau",
		Alpha2:          "GW",
		Alpha3:          "GNB",
		ISO:             "624",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Германия",
		FullName:        "Федеративная Республика Германия",
		English:         "Germany",
		Alpha2:          "DE",
		Alpha3:          "DEU",
		ISO:             "276",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Гернси",
		FullName:        "",
		English:         "Guernsey",
		Alpha2:          "GG",
		Alpha3:          "GGY",
		ISO:             "831",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Гибралтар",
		FullName:        "",
		English:         "Gibraltar",
		Alpha2:          "GI",
		Alpha3:          "GIB",
		ISO:             "292",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Гондурас",
		FullName:        "Республика Гондурас",
		English:         "Honduras",
		Alpha2:          "HN",
		Alpha3:          "HND",
		ISO:             "340",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Гонконг",
		FullName:        "Специальный  административный  регион Китая Гонконг",
		English:         "Hong Kong",
		Alpha2:          "HK",
		Alpha3:          "HKG",
		ISO:             "344",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Гренада",
		FullName:        "",
		English:         "Grenada",
		Alpha2:          "GD",
		Alpha3:          "GRD",
		ISO:             "308",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Гренландия",
		FullName:        "",
		English:         "Greenland",
		Alpha2:          "GL",
		Alpha3:          "GRL",
		ISO:             "304",
		Location:        "Америка",
		LocationPrecise: "Северная Америка",
	},
	{
		Name:            "Греция",
		FullName:        "Греческая Республика",
		English:         "Greece",
		Alpha2:          "GR",
		Alpha3:          "GRC",
		ISO:             "300",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Грузия",
		FullName:        "",
		English:         "Georgia",
		Alpha2:          "GE",
		Alpha3:          "GEO",
		ISO:             "268",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Гуам",
		FullName:        "",
		English:         "Guam",
		Alpha2:          "GU",
		Alpha3:          "GUM",
		ISO:             "316",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Дания",
		FullName:        "Королевство Дания",
		English:         "Denmark",
		Alpha2:          "DK",
		Alpha3:          "DNK",
		ISO:             "208",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Джерси",
		FullName:        "",
		English:         "Jersey",
		Alpha2:          "JE",
		Alpha3:          "JEY",
		ISO:             "832",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Джибути",
		FullName:        "Республика Джибути",
		English:         "Djibouti",
		Alpha2:          "DJ",
		Alpha3:          "DJI",
		ISO:             "262",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Доминика",
		FullName:        "Содружество Доминики",
		English:         "Dominica",
		Alpha2:          "DM",
		Alpha3:          "DMA",
		ISO:             "212",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Доминиканская Республика",
		FullName:        "",
		English:         "Dominican Republic",
		Alpha2:          "DO",
		Alpha3:          "DOM",
		ISO:             "214",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Египет",
		FullName:        "Арабская Республика Египет",
		English:         "Egypt",
		Alpha2:          "EG",
		Alpha3:          "EGY",
		ISO:             "818",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Замбия",
		FullName:        "Республика Замбия",
		English:         "Zambia",
		Alpha2:          "ZM",
		Alpha3:          "ZMB",
		ISO:             "894",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Западная Сахара",
		FullName:        "",
		English:         "Western Sahara",
		Alpha2:          "EH",
		Alpha3:          "ESH",
		ISO:             "732",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Зимбабве",
		FullName:        "Республика Зимбабве",
		English:         "Zimbabwe",
		Alpha2:          "ZW",
		Alpha3:          "ZWE",
		ISO:             "716",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Израиль",
		FullName:        "Государство Израиль",
		English:         "Israel",
		Alpha2:          "IL",
		Alpha3:          "ISR",
		ISO:             "376",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Индия",
		FullName:        "Республика Индия",
		English:         "India",
		Alpha2:          "IN",
		Alpha3:          "IND",
		ISO:             "356",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Индонезия",
		FullName:        "Республика Индонезия",
		English:         "Indonesia",
		Alpha2:          "ID",
		Alpha3:          "IDN",
		ISO:             "360",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Иордания",
		FullName:        "Иорданское Хашимитское Королевство",
		English:         "Jordan",
		Alpha2:          "JO",
		Alpha3:          "JOR",
		ISO:             "400",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Ирак",
		FullName:        "Республика Ирак",
		English:         "Iraq",
		Alpha2:          "IQ",
		Alpha3:          "IRQ",
		ISO:             "368",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Иран, Исламская Республика",
		FullName:        "Исламская Республика Иран",
		English:         "Iran, Islamic Republic of",
		Alpha2:          "IR",
		Alpha3:          "IRN",
		ISO:             "364",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Ирландия",
		FullName:        "",
		English:         "Ireland",
		Alpha2:          "IE",
		Alpha3:          "IRL",
		ISO:             "372",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Исландия",
		FullName:        "Республика Исландия",
		English:         "Iceland",
		Alpha2:          "IS",
		Alpha3:          "ISL",
		ISO:             "352",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Испания",
		FullName:        "Королевство Испания",
		English:         "Spain",
		Alpha2:          "ES",
		Alpha3:          "ESP",
		ISO:             "724",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Италия",
		FullName:        "Итальянская Республика",
		English:         "Italy",
		Alpha2:          "IT",
		Alpha3:          "ITA",
		ISO:             "380",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Йемен",
		FullName:        "Йеменская Республика",
		English:         "Yemen",
		Alpha2:          "YE",
		Alpha3:          "YEM",
		ISO:             "887",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Кабо-Верде",
		FullName:        "Республика Кабо-Верде",
		English:         "Cape Verde",
		Alpha2:          "CV",
		Alpha3:          "CPV",
		ISO:             "132",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Казахстан",
		FullName:        "Республика Казахстан",
		English:         "Kazakhstan",
		Alpha2:          "KZ",
		Alpha3:          "KAZ",
		ISO:             "398",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Камбоджа",
		FullName:        "Королевство Камбоджа",
		English:         "Cambodia",
		Alpha2:          "KH",
		Alpha3:          "KHM",
		ISO:             "116",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Камерун",
		FullName:        "Республика Камерун",
		English:         "Cameroon",
		Alpha2:          "CM",
		Alpha3:          "CMR",
		ISO:             "120",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Канада",
		FullName:        "",
		English:         "Canada",
		Alpha2:          "CA",
		Alpha3:          "CAN",
		ISO:             "124",
		Location:        "Америка",
		LocationPrecise: "Северная Америка",
	},
	{
		Name:            "Катар",
		FullName:        "Государство Катар",
		English:         "Qatar",
		Alpha2:          "QA",
		Alpha3:          "QAT",
		ISO:             "634",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Кения",
		FullName:        "Республика Кения",
		English:         "Kenya",
		Alpha2:          "KE",
		Alpha3:          "KEN",
		ISO:             "404",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Кипр",
		FullName:        "Республика Кипр",
		English:         "Cyprus",
		Alpha2:          "CY",
		Alpha3:          "CYP",
		ISO:             "196",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Киргизия",
		FullName:        "Киргизская Республика",
		English:         "Kyrgyzstan",
		Alpha2:          "KG",
		Alpha3:          "KGZ",
		ISO:             "417",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Кирибати",
		FullName:        "Республика Кирибати",
		English:         "Kiribati",
		Alpha2:          "KI",
		Alpha3:          "KIR",
		ISO:             "296",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Китай",
		FullName:        "Китайская Народная Республика",
		English:         "China",
		Alpha2:          "CN",
		Alpha3:          "CHN",
		ISO:             "156",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Кокосовые (Килинг) острова",
		FullName:        "",
		English:         "Cocos (Keeling) Islands",
		Alpha2:          "CC",
		Alpha3:          "CCK",
		ISO:             "166",
		Location:        "Океания",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Колумбия",
		FullName:        "Республика Колумбия",
		English:         "Colombia",
		Alpha2:          "CO",
		Alpha3:          "COL",
		ISO:             "170",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Коморы",
		FullName:        "Союз Коморы",
		English:         "Comoros",
		Alpha2:          "KM",
		Alpha3:          "COM",
		ISO:             "174",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Конго",
		FullName:        "Республика Конго",
		English:         "Congo",
		Alpha2:          "CG",
		Alpha3:          "COG",
		ISO:             "178",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Конго, Демократическая Республика",
		FullName:        "Демократическая Республика Конго",
		English:         "Congo, Democratic Republic of the",
		Alpha2:          "CD",
		Alpha3:          "COD",
		ISO:             "180",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Корея, Народно-Демократическая Республика",
		FullName:        "Корейская Народно-Демократическая Республика",
		English:         "Korea, Democratic People's republic of",
		Alpha2:          "KP",
		Alpha3:          "PRK",
		ISO:             "408",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Корея, Республика",
		FullName:        "Республика Корея",
		English:         "Korea, Republic of",
		Alpha2:          "KR",
		Alpha3:          "KOR",
		ISO:             "410",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Коста-Рика",
		FullName:        "Республика Коста-Рика",
		English:         "Costa Rica",
		Alpha2:          "CR",
		Alpha3:          "CRI",
		ISO:             "188",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Кот д'Ивуар",
		FullName:        "Республика Кот д'Ивуар",
		English:         "Cote d'Ivoire",
		Alpha2:          "CI",
		Alpha3:          "CIV",
		ISO:             "384",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Куба",
		FullName:        "Республика Куба",
		English:         "Cuba",
		Alpha2:          "CU",
		Alpha3:          "CUB",
		ISO:             "192",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Кувейт",
		FullName:        "Государство Кувейт",
		English:         "Kuwait",
		Alpha2:          "KW",
		Alpha3:          "KWT",
		ISO:             "414",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Кюрасао",
		FullName:        "",
		English:         "Curaçao",
		Alpha2:          "CW",
		Alpha3:          "CUW",
		ISO:             "531",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Лаос",
		FullName:        "Лаосская Народно-Демократическая Республика",
		English:         "Lao People's Democratic Republic",
		Alpha2:          "LA",
		Alpha3:          "LAO",
		ISO:             "418",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Латвия",
		FullName:        "Латвийская Республика",
		English:         "Latvia",
		Alpha2:          "LV",
		Alpha3:          "LVA",
		ISO:             "428",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Лесото",
		FullName:        "Королевство Лесото",
		English:         "Lesotho",
		Alpha2:          "LS",
		Alpha3:          "LSO",
		ISO:             "426",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Ливан",
		FullName:        "Ливанская Республика",
		English:         "Lebanon",
		Alpha2:          "LB",
		Alpha3:          "LBN",
		ISO:             "422",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Ливийская Арабская Джамахирия",
		FullName:        "Социалистическая Народная Ливийская Арабская Джамахирия",
		English:         "Libyan Arab Jamahiriya",
		Alpha2:          "LY",
		Alpha3:          "LBY",
		ISO:             "434",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Либерия",
		FullName:        "Республика Либерия",
		English:         "Liberia",
		Alpha2:          "LR",
		Alpha3:          "LBR",
		ISO:             "430",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Лихтенштейн",
		FullName:        "Княжество Лихтенштейн",
		English:         "Liechtenstein",
		Alpha2:          "LI",
		Alpha3:          "LIE",
		ISO:             "438",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Литва",
		FullName:        "Литовская Республика",
		English:         "Lithuania",
		Alpha2:          "LT",
		Alpha3:          "LTU",
		ISO:             "440",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Люксембург",
		FullName:        "Великое Герцогство Люксембург",
		English:         "Luxembourg",
		Alpha2:          "LU",
		Alpha3:          "LUX",
		ISO:             "442",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Маврикий",
		FullName:        "Республика Маврикий",
		English:         "Mauritius",
		Alpha2:          "MU",
		Alpha3:          "MUS",
		ISO:             "480",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Мавритания",
		FullName:        "Исламская Республика Мавритания",
		English:         "Mauritania",
		Alpha2:          "MR",
		Alpha3:          "MRT",
		ISO:             "478",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Мадагаскар",
		FullName:        "Республика Мадагаскар",
		English:         "Madagascar",
		Alpha2:          "MG",
		Alpha3:          "MDG",
		ISO:             "450",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Майотта",
		FullName:        "",
		English:         "Mayotte",
		Alpha2:          "YT",
		Alpha3:          "MYT",
		ISO:             "175",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Макао",
		FullName:        "Специальный административный регион Китая Макао",
		English:         "Macao",
		Alpha2:          "MO",
		Alpha3:          "MAC",
		ISO:             "446",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Малави",
		FullName:        "Республика Малави",
		English:         "Malawi",
		Alpha2:          "MW",
		Alpha3:          "MWI",
		ISO:             "454",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Малайзия",
		FullName:        "",
		English:         "Malaysia",
		Alpha2:          "MY",
		Alpha3:          "MYS",
		ISO:             "458",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Мали",
		FullName:        "Республика Мали",
		English:         "Mali",
		Alpha2:          "ML",
		Alpha3:          "MLI",
		ISO:             "466",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Малые Тихоокеанские отдаленные острова Соединенных Штатов",
		FullName:        "",
		English:         "United States Minor Outlying Islands",
		Alpha2:          "UM",
		Alpha3:          "UMI",
		ISO:             "581",
		Location:        "Океания",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Мальдивы",
		FullName:        "Мальдивская Республика",
		English:         "Maldives",
		Alpha2:          "MV",
		Alpha3:          "MDV",
		ISO:             "462",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Мальта",
		FullName:        "Республика Мальта",
		English:         "Malta",
		Alpha2:          "MT",
		Alpha3:          "MLT",
		ISO:             "470",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Марокко",
		FullName:        "Королевство Марокко",
		English:         "Morocco",
		Alpha2:          "MA",
		Alpha3:          "MAR",
		ISO:             "504",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Мартиника",
		FullName:        "",
		English:         "Martinique",
		Alpha2:          "MQ",
		Alpha3:          "MTQ",
		ISO:             "474",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Маршалловы острова",
		FullName:        "Республика Маршалловы острова",
		English:         "Marshall Islands",
		Alpha2:          "MH",
		Alpha3:          "MHL",
		ISO:             "584",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Мексика",
		FullName:        "Мексиканские Соединенные Штаты",
		English:         "Mexico",
		Alpha2:          "MX",
		Alpha3:          "MEX",
		ISO:             "484",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Микронезия, Федеративные Штаты",
		FullName:        "Федеративные штаты Микронезии",
		English:         "Micronesia, Federated States of",
		Alpha2:          "FM",
		Alpha3:          "FSM",
		ISO:             "583",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Мозамбик",
		FullName:        "Республика Мозамбик",
		English:         "Mozambique",
		Alpha2:          "MZ",
		Alpha3:          "MOZ",
		ISO:             "508",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Молдова, Республика",
		FullName:        "Республика Молдова",
		English:         "Moldova",
		Alpha2:          "MD",
		Alpha3:          "MDA",
		ISO:             "498",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Монако",
		FullName:        "Княжество Монако",
		English:         "Monaco",
		Alpha2:          "MC",
		Alpha3:          "MCO",
		ISO:             "492",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Монголия",
		FullName:        "",
		English:         "Mongolia",
		Alpha2:          "MN",
		Alpha3:          "MNG",
		ISO:             "496",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Монтсеррат",
		FullName:        "",
		English:         "Montserrat",
		Alpha2:          "MS",
		Alpha3:          "MSR",
		ISO:             "500",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Мьянма",
		FullName:        "Союз Мьянма",
		English:         "Burma",
		Alpha2:          "MM",
		Alpha3:          "MMR",
		ISO:             "104",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Намибия",
		FullName:        "Республика Намибия",
		English:         "Namibia",
		Alpha2:          "NA",
		Alpha3:          "NAM",
		ISO:             "516",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Науру",
		FullName:        "Республика Науру",
		English:         "Nauru",
		Alpha2:          "NR",
		Alpha3:          "NRU",
		ISO:             "520",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Непал",
		FullName:        "Королевство Непал",
		English:         "Nepal",
		Alpha2:          "NP",
		Alpha3:          "NPL",
		ISO:             "524",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Нигер",
		FullName:        "Республика Нигер",
		English:         "Niger",
		Alpha2:          "NE",
		Alpha3:          "NER",
		ISO:             "562",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Нигерия",
		FullName:        "Федеративная Республика Нигерия",
		English:         "Nigeria",
		Alpha2:          "NG",
		Alpha3:          "NGA",
		ISO:             "566",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Нидерланды",
		FullName:        "Королевство Нидерландов",
		English:         "Netherlands",
		Alpha2:          "NL",
		Alpha3:          "NLD",
		ISO:             "528",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Никарагуа",
		FullName:        "Республика Никарагуа",
		English:         "Nicaragua",
		Alpha2:          "NI",
		Alpha3:          "NIC",
		ISO:             "558",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Ниуэ",
		FullName:        "Республика Ниуэ",
		English:         "Niue",
		Alpha2:          "NU",
		Alpha3:          "NIU",
		ISO:             "570",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Новая Зеландия",
		FullName:        "",
		English:         "New Zealand",
		Alpha2:          "NZ",
		Alpha3:          "NZL",
		ISO:             "554",
		Location:        "Океания",
		LocationPrecise: "Австралия и Новая Зеландия",
	},
	{
		Name:            "Новая Каледония",
		FullName:        "",
		English:         "New Caledonia",
		Alpha2:          "NC",
		Alpha3:          "NCL",
		ISO:             "540",
		Location:        "Океания",
		LocationPrecise: "Меланезия",
	},
	{
		Name:            "Норвегия",
		FullName:        "Королевство Норвегия",
		English:         "Norway",
		Alpha2:          "NO",
		Alpha3:          "NOR",
		ISO:             "578",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "ОАЭ",
		FullName:        "Объединенные Арабские Эмираты",
		English:         "United Arab Emirates",
		Alpha2:          "AE",
		Alpha3:          "ARE",
		ISO:             "784",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Оман",
		FullName:        "Султанат Оман",
		English:         "Oman",
		Alpha2:          "OM",
		Alpha3:          "OMN",
		ISO:             "512",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Остров Буве",
		FullName:        "Остров Буве",
		English:         "Bouvet Island",
		Alpha2:          "BV",
		Alpha3:          "BVT",
		ISO:             "074",
		Location:        "",
		LocationPrecise: "Южный океан",
	},
	{
		Name:            "Остров Мэн",
		FullName:        "Остров Мэн",
		English:         "Isle of Man",
		Alpha2:          "IM",
		Alpha3:          "IMN",
		ISO:             "833",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Остров Норфолк",
		FullName:        "Остров Норфолк",
		English:         "Norfolk Island",
		Alpha2:          "NF",
		Alpha3:          "NFK",
		ISO:             "574",
		Location:        "Океания",
		LocationPrecise: "Австралия и Новая Зеландия",
	},
	{
		Name:            "Остров Рождества",
		FullName:        "Остров Рождества",
		English:         "Christmas Island",
		Alpha2:          "CX",
		Alpha3:          "CXR",
		ISO:             "162",
		Location:        "Азия",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Херд и Макдональд",
		FullName:        "Остров Херд и острова Макдональд",
		English:         "Heard Island and McDonald Islands",
		Alpha2:          "HM",
		Alpha3:          "HMD",
		ISO:             "334",
		Location:        "",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Острова Кайман",
		FullName:        "",
		English:         "Cayman Islands",
		Alpha2:          "KY",
		Alpha3:          "CYM",
		ISO:             "136",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Острова Кука",
		FullName:        "",
		English:         "Cook Islands",
		Alpha2:          "CK",
		Alpha3:          "COK",
		ISO:             "184",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Острова Теркс и Кайкос",
		FullName:        "",
		English:         "Turks and Caicos Islands",
		Alpha2:          "TC",
		Alpha3:          "TCA",
		ISO:             "796",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Пакистан",
		FullName:        "Исламская Республика Пакистан",
		English:         "Pakistan",
		Alpha2:          "PK",
		Alpha3:          "PAK",
		ISO:             "586",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Палау",
		FullName:        "Республика Палау",
		English:         "Palau",
		Alpha2:          "PW",
		Alpha3:          "PLW",
		ISO:             "585",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Палестинская территория, оккупированная",
		FullName:        "Оккупированная Палестинская территория",
		English:         "Palestinian Territory, Occupied",
		Alpha2:          "PS",
		Alpha3:          "PSE",
		ISO:             "275",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Панама",
		FullName:        "Республика Панама",
		English:         "Panama",
		Alpha2:          "PA",
		Alpha3:          "PAN",
		ISO:             "591",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Папский Престол (Государство &mdash; город Ватикан)",
		FullName:        "",
		English:         "Holy See (Vatican City State)",
		Alpha2:          "VA",
		Alpha3:          "VAT",
		ISO:             "336",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Папуа-Новая Гвинея",
		FullName:        "",
		English:         "Papua New Guinea",
		Alpha2:          "PG",
		Alpha3:          "PNG",
		ISO:             "598",
		Location:        "Океания",
		LocationPrecise: "Меланезия",
	},
	{
		Name:            "Парагвай",
		FullName:        "Республика Парагвай",
		English:         "Paraguay",
		Alpha2:          "PY",
		Alpha3:          "PRY",
		ISO:             "600",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Перу",
		FullName:        "Республика Перу",
		English:         "Peru",
		Alpha2:          "PE",
		Alpha3:          "PER",
		ISO:             "604",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Питкерн",
		FullName:        "",
		English:         "Pitcairn",
		Alpha2:          "PN",
		Alpha3:          "PCN",
		ISO:             "612",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Польша",
		FullName:        "Республика Польша",
		English:         "Poland",
		Alpha2:          "PL",
		Alpha3:          "POL",
		ISO:             "616",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Португалия",
		FullName:        "Португальская Республика",
		English:         "Portugal",
		Alpha2:          "PT",
		Alpha3:          "PRT",
		ISO:             "620",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Пуэрто-Рико",
		FullName:        "",
		English:         "Puerto Rico",
		Alpha2:          "PR",
		Alpha3:          "PRI",
		ISO:             "630",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Македония",
		FullName:        "Республика Македония",
		English:         "Macedonia, The Former Yugoslav Republic Of",
		Alpha2:          "MK",
		Alpha3:          "MKD",
		ISO:             "807",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Реюньон",
		FullName:        "",
		English:         "Reunion",
		Alpha2:          "RE",
		Alpha3:          "REU",
		ISO:             "638",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Россия",
		FullName:        "Российская Федерация",
		English:         "Russian Federation",
		Alpha2:          "RU",
		Alpha3:          "RUS",
		ISO:             "643",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Руанда",
		FullName:        "Руандийская Республика",
		English:         "Rwanda",
		Alpha2:          "RW",
		Alpha3:          "RWA",
		ISO:             "646",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Румыния",
		FullName:        "",
		English:         "Romania",
		Alpha2:          "RO",
		Alpha3:          "ROU",
		ISO:             "642",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Самоа",
		FullName:        "Независимое Государство Самоа",
		English:         "Samoa",
		Alpha2:          "WS",
		Alpha3:          "WSM",
		ISO:             "882",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Сан-Марино",
		FullName:        "Республика Сан-Марино",
		English:         "San Marino",
		Alpha2:          "SM",
		Alpha3:          "SMR",
		ISO:             "674",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Сан-Томе и Принсипи",
		FullName:        "Демократическая Республика Сан-Томе и Принсипи",
		English:         "Sao Tome and Principe",
		Alpha2:          "ST",
		Alpha3:          "STP",
		ISO:             "678",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Саудовская Аравия",
		FullName:        "Королевство Саудовская Аравия",
		English:         "Saudi Arabia",
		Alpha2:          "SA",
		Alpha3:          "SAU",
		ISO:             "682",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Свазиленд",
		FullName:        "Королевство Свазиленд",
		English:         "Swaziland",
		Alpha2:          "SZ",
		Alpha3:          "SWZ",
		ISO:             "748",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Святая Елена, Остров вознесения, Тристан-да-Кунья",
		FullName:        "",
		English:         "Saint Helena, Ascension And Tristan Da Cunha",
		Alpha2:          "SH",
		Alpha3:          "SHN",
		ISO:             "654",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Северные Марианские острова",
		FullName:        "Содружество Северных Марианских островов",
		English:         "Northern Mariana Islands",
		Alpha2:          "MP",
		Alpha3:          "MNP",
		ISO:             "580",
		Location:        "Океания",
		LocationPrecise: "Микронезия",
	},
	{
		Name:            "Сен-Бартельми",
		FullName:        "",
		English:         "Saint Barthélemy",
		Alpha2:          "BL",
		Alpha3:          "BLM",
		ISO:             "652",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сен-Мартен",
		FullName:        "",
		English:         "Saint Martin (French Part)",
		Alpha2:          "MF",
		Alpha3:          "MAF",
		ISO:             "663",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сенегал",
		FullName:        "Республика Сенегал",
		English:         "Senegal",
		Alpha2:          "SN",
		Alpha3:          "SEN",
		ISO:             "686",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Сент-Винсент и Гренадины",
		FullName:        "",
		English:         "Saint Vincent and the Grenadines",
		Alpha2:          "VC",
		Alpha3:          "VCT",
		ISO:             "670",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сент-Китс и Невис",
		FullName:        "",
		English:         "Saint Kitts and Nevis",
		Alpha2:          "KN",
		Alpha3:          "KNA",
		ISO:             "659",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сент-Люсия",
		FullName:        "",
		English:         "Saint Lucia",
		Alpha2:          "LC",
		Alpha3:          "LCA",
		ISO:             "662",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сент-Пьер и Микелон",
		FullName:        "",
		English:         "Saint Pierre and Miquelon",
		Alpha2:          "PM",
		Alpha3:          "SPM",
		ISO:             "666",
		Location:        "Америка",
		LocationPrecise: "Северная Америка",
	},
	{
		Name:            "Сербия",
		FullName:        "Республика Сербия",
		English:         "Serbia",
		Alpha2:          "RS",
		Alpha3:          "SRB",
		ISO:             "688",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Сейшелы",
		FullName:        "Республика Сейшелы",
		English:         "Seychelles",
		Alpha2:          "SC",
		Alpha3:          "SYC",
		ISO:             "690",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Сингапур",
		FullName:        "Республика Сингапур",
		English:         "Singapore",
		Alpha2:          "SG",
		Alpha3:          "SGP",
		ISO:             "702",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Синт-Мартен",
		FullName:        "",
		English:         "Sint Maarten",
		Alpha2:          "SX",
		Alpha3:          "SXM",
		ISO:             "534",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Сирия",
		FullName:        "Сирийская Арабская Республика",
		English:         "Syrian Arab Republic",
		Alpha2:          "SY",
		Alpha3:          "SYR",
		ISO:             "760",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Словакия",
		FullName:        "Словацкая Республика",
		English:         "Slovakia",
		Alpha2:          "SK",
		Alpha3:          "SVK",
		ISO:             "703",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Словения",
		FullName:        "Республика Словения",
		English:         "Slovenia",
		Alpha2:          "SI",
		Alpha3:          "SVN",
		ISO:             "705",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Великобритания",
		FullName:        "Соединенное Королевство Великобритании и Северной Ирландии",
		English:         "United Kingdom",
		Alpha2:          "GB",
		Alpha3:          "GBR",
		ISO:             "826",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Соединенные Штаты",
		FullName:        "Соединенные Штаты Америки",
		English:         "United States",
		Alpha2:          "US",
		Alpha3:          "USA",
		ISO:             "840",
		Location:        "Америка",
		LocationPrecise: "Северная Америка",
	},
	{
		Name:            "Соломоновы острова",
		FullName:        "",
		English:         "Solomon Islands",
		Alpha2:          "SB",
		Alpha3:          "SLB",
		ISO:             "090",
		Location:        "Океания",
		LocationPrecise: "Меланезия",
	},
	{
		Name:            "Сомали",
		FullName:        "Сомалийская Республика",
		English:         "Somalia",
		Alpha2:          "SO",
		Alpha3:          "SOM",
		ISO:             "706",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Судан",
		FullName:        "Республика Судан",
		English:         "Sudan",
		Alpha2:          "SD",
		Alpha3:          "SDN",
		ISO:             "736",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Суринам",
		FullName:        "Республика Суринам",
		English:         "Suriname",
		Alpha2:          "SR",
		Alpha3:          "SUR",
		ISO:             "740",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Сьерра-Леоне",
		FullName:        "Республика Сьерра-Леоне",
		English:         "Sierra Leone",
		Alpha2:          "SL",
		Alpha3:          "SLE",
		ISO:             "694",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Таджикистан",
		FullName:        "Республика Таджикистан",
		English:         "Tajikistan",
		Alpha2:          "TJ",
		Alpha3:          "TJK",
		ISO:             "762",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Таиланд",
		FullName:        "Королевство Таиланд",
		English:         "Thailand",
		Alpha2:          "TH",
		Alpha3:          "THA",
		ISO:             "764",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Тайвань (Китай)",
		FullName:        "",
		English:         "Taiwan, Province of China",
		Alpha2:          "TW",
		Alpha3:          "TWN",
		ISO:             "158",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	},
	{
		Name:            "Танзания, Объединенная Республика",
		FullName:        "Объединенная Республика Танзания",
		English:         "Tanzania, United Republic Of",
		Alpha2:          "TZ",
		Alpha3:          "TZA",
		ISO:             "834",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Тимор-Лесте",
		FullName:        "Демократическая Республика Тимор-Лесте",
		English:         "Timor-Leste",
		Alpha2:          "TL",
		Alpha3:          "TLS",
		ISO:             "626",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Того",
		FullName:        "Тоголезская Республика",
		English:         "Togo",
		Alpha2:          "TG",
		Alpha3:          "TGO",
		ISO:             "768",
		Location:        "Африка",
		LocationPrecise: "Западная Африка",
	},
	{
		Name:            "Токелау",
		FullName:        "",
		English:         "Tokelau",
		Alpha2:          "TK",
		Alpha3:          "TKL",
		ISO:             "772",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Тонга",
		FullName:        "Королевство Тонга",
		English:         "Tonga",
		Alpha2:          "TO",
		Alpha3:          "TON",
		ISO:             "776",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Тринидад и Тобаго",
		FullName:        "Республика Тринидад и Тобаго",
		English:         "Trinidad and Tobago",
		Alpha2:          "TT",
		Alpha3:          "TTO",
		ISO:             "780",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Тувалу",
		FullName:        "",
		English:         "Tuvalu",
		Alpha2:          "TV",
		Alpha3:          "TUV",
		ISO:             "798",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Тунис",
		FullName:        "Тунисская Республика",
		English:         "Tunisia",
		Alpha2:          "TN",
		Alpha3:          "TUN",
		ISO:             "788",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Туркмения",
		FullName:        "Туркменистан",
		English:         "Turkmenistan",
		Alpha2:          "TM",
		Alpha3:          "TKM",
		ISO:             "795",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Турция",
		FullName:        "Турецкая Республика",
		English:         "Turkey",
		Alpha2:          "TR",
		Alpha3:          "TUR",
		ISO:             "792",
		Location:        "Азия",
		LocationPrecise: "Западная Азия",
	},
	{
		Name:            "Уганда",
		FullName:        "Республика Уганда",
		English:         "Uganda",
		Alpha2:          "UG",
		Alpha3:          "UGA",
		ISO:             "800",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Узбекистан",
		FullName:        "Республика Узбекистан",
		English:         "Uzbekistan",
		Alpha2:          "UZ",
		Alpha3:          "UZB",
		ISO:             "860",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Украина",
		FullName:        "",
		English:         "Ukraine",
		Alpha2:          "UA",
		Alpha3:          "UKR",
		ISO:             "804",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Уоллис и Футуна",
		FullName:        "",
		English:         "Wallis and Futuna",
		Alpha2:          "WF",
		Alpha3:          "WLF",
		ISO:             "876",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Уругвай",
		FullName:        "Восточная Республика Уругвай",
		English:         "Uruguay",
		Alpha2:          "UY",
		Alpha3:          "URY",
		ISO:             "858",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Фарерские острова",
		FullName:        "",
		English:         "Faroe Islands",
		Alpha2:          "FO",
		Alpha3:          "FRO",
		ISO:             "234",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Фиджи",
		FullName:        "Республика островов Фиджи",
		English:         "Fiji",
		Alpha2:          "FJ",
		Alpha3:          "FJI",
		ISO:             "242",
		Location:        "Океания",
		LocationPrecise: "Меланезия",
	},
	{
		Name:            "Филиппины",
		FullName:        "Республика Филиппины",
		English:         "Philippines",
		Alpha2:          "PH",
		Alpha3:          "PHL",
		ISO:             "608",
		Location:        "Азия",
		LocationPrecise: "Юго-Восточная Азия",
	},
	{
		Name:            "Финляндия",
		FullName:        "Финляндская Республика",
		English:         "Finland",
		Alpha2:          "FI",
		Alpha3:          "FIN",
		ISO:             "246",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Фолклендские острова (Мальвинские)",
		FullName:        "",
		English:         "Falkland Islands (Malvinas)",
		Alpha2:          "FK",
		Alpha3:          "FLK",
		ISO:             "238",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Франция",
		FullName:        "Французская Республика",
		English:         "France",
		Alpha2:          "FR",
		Alpha3:          "FRA",
		ISO:             "250",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Французская Гвиана",
		FullName:        "",
		English:         "French Guiana",
		Alpha2:          "GF",
		Alpha3:          "GUF",
		ISO:             "254",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Французская Полинезия",
		FullName:        "",
		English:         "French Polynesia",
		Alpha2:          "PF",
		Alpha3:          "PYF",
		ISO:             "258",
		Location:        "Океания",
		LocationPrecise: "Полинезия",
	},
	{
		Name:            "Французские Южные территории",
		FullName:        "",
		English:         "French Southern Territories",
		Alpha2:          "TF",
		Alpha3:          "ATF",
		ISO:             "260",
		Location:        "",
		LocationPrecise: "Индийский океан",
	},
	{
		Name:            "Хорватия",
		FullName:        "Республика Хорватия",
		English:         "Croatia",
		Alpha2:          "HR",
		Alpha3:          "HRV",
		ISO:             "191",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Центрально-Африканская Республика",
		FullName:        "",
		English:         "Central African Republic",
		Alpha2:          "CF",
		Alpha3:          "CAF",
		ISO:             "140",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Чад",
		FullName:        "Республика Чад",
		English:         "Chad",
		Alpha2:          "TD",
		Alpha3:          "TCD",
		ISO:             "148",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Черногория",
		FullName:        "Республика Черногория",
		English:         "Montenegro",
		Alpha2:          "ME",
		Alpha3:          "MNE",
		ISO:             "499",
		Location:        "Европа",
		LocationPrecise: "Южная Европа",
	},
	{
		Name:            "Чехия",
		FullName:        "Чешская Республика",
		English:         "Czech Republic",
		Alpha2:          "CZ",
		Alpha3:          "CZE",
		ISO:             "203",
		Location:        "Европа",
		LocationPrecise: "Восточная Европа",
	},
	{
		Name:            "Чили",
		FullName:        "Республика Чили",
		English:         "Chile",
		Alpha2:          "CL",
		Alpha3:          "CHL",
		ISO:             "152",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Швейцария",
		FullName:        "Швейцарская Конфедерация",
		English:         "Switzerland",
		Alpha2:          "CH",
		Alpha3:          "CHE",
		ISO:             "756",
		Location:        "Европа",
		LocationPrecise: "Западная Европа",
	},
	{
		Name:            "Швеция",
		FullName:        "Королевство Швеция",
		English:         "Sweden",
		Alpha2:          "SE",
		Alpha3:          "SWE",
		ISO:             "752",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Шпицберген и Ян Майен",
		FullName:        "",
		English:         "Svalbard and Jan Mayen",
		Alpha2:          "SJ",
		Alpha3:          "SJM",
		ISO:             "744",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Шри-Ланка",
		FullName:        "Демократическая Социалистическая Республика Шри-Ланка",
		English:         "Sri Lanka",
		Alpha2:          "LK",
		Alpha3:          "LKA",
		ISO:             "144",
		Location:        "Азия",
		LocationPrecise: "Южная часть Центральной Азии",
	},
	{
		Name:            "Эквадор",
		FullName:        "Республика Эквадор",
		English:         "Ecuador",
		Alpha2:          "EC",
		Alpha3:          "ECU",
		ISO:             "218",
		Location:        "Америка",
		LocationPrecise: "Южная Америка",
	},
	{
		Name:            "Экваториальная Гвинея",
		FullName:        "Республика Экваториальная Гвинея",
		English:         "Equatorial Guinea",
		Alpha2:          "GQ",
		Alpha3:          "GNQ",
		ISO:             "226",
		Location:        "Африка",
		LocationPrecise: "Центральная Африка",
	},
	{
		Name:            "Эландские острова",
		FullName:        "",
		English:         "Åland Islands",
		Alpha2:          "AX",
		Alpha3:          "ALA",
		ISO:             "248",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Эль-Сальвадор",
		FullName:        "Республика Эль-Сальвадор",
		English:         "El Salvador",
		Alpha2:          "SV",
		Alpha3:          "SLV",
		ISO:             "222",
		Location:        "Америка",
		LocationPrecise: "Центральная Америка",
	},
	{
		Name:            "Эритрея",
		FullName:        "",
		English:         "Eritrea",
		Alpha2:          "ER",
		Alpha3:          "ERI",
		ISO:             "232",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Эстония",
		FullName:        "Эстонская Республика",
		English:         "Estonia",
		Alpha2:          "EE",
		Alpha3:          "EST",
		ISO:             "233",
		Location:        "Европа",
		LocationPrecise: "Северная Европа",
	},
	{
		Name:            "Эфиопия",
		FullName:        "Федеративная Демократическая Республика Эфиопия",
		English:         "Ethiopia",
		Alpha2:          "ET",
		Alpha3:          "ETH",
		ISO:             "231",
		Location:        "Африка",
		LocationPrecise: "Восточная Африка",
	},
	{
		Name:            "Южная Африка",
		FullName:        "Южно-Африканская Республика",
		English:         "South Africa",
		Alpha2:          "ZA",
		Alpha3:          "ZAF",
		ISO:             "710",
		Location:        "Африка",
		LocationPrecise: "Южная часть Африки",
	},
	{
		Name:            "Южная Джорджия и Южные Сандвичевы острова",
		FullName:        "",
		English:         "South Georgia and the South Sandwich Islands",
		Alpha2:          "GS",
		Alpha3:          "SGS",
		ISO:             "239",
		Location:        "",
		LocationPrecise: "Южный океан",
	},
	{
		Name:            "Южная Осетия",
		FullName:        "Республика Южная Осетия",
		English:         "South Ossetia",
		Alpha2:          "OS",
		Alpha3:          "OST",
		ISO:             "896",
		Location:        "Азия",
		LocationPrecise: "Закавказье",
	},
	{
		Name:            "Южный Судан",
		FullName:        "",
		English:         "South Sudan",
		Alpha2:          "SS",
		Alpha3:          "SSD",
		ISO:             "728",
		Location:        "Африка",
		LocationPrecise: "Северная Африка",
	},
	{
		Name:            "Ямайка",
		FullName:        "",
		English:         "Jamaica",
		Alpha2:          "JM",
		Alpha3:          "JAM",
		ISO:             "388",
		Location:        "Америка",
		LocationPrecise: "Карибский бассейн",
	},
	{
		Name:            "Япония",
		FullName:        "",
		English:         "Japan",
		Alpha2:          "JP",
		Alpha3:          "JPN",
		ISO:             "392",
		Location:        "Азия",
		LocationPrecise: "Восточная Азия",
	}}
